// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1Z34gIp8xK4Expf2OUrqfMe9jeZqC14',
    appId: '1:371815697931:web:f33f3fb2ac0efc9473c10e',
    messagingSenderId: '371815697931',
    projectId: 'keuangan-e5487',
    authDomain: 'keuangan-e5487.firebaseapp.com',
    storageBucket: 'keuangan-e5487.appspot.com',
    measurementId: 'G-935V70PS63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfEC5D5kgBC8sCsCAasG3erpBKX2N7mo',
    appId: '1:229689037563:android:d51a67fcd410d529a0965e',
    messagingSenderId: '229689037563',
    projectId: 'bundahara-a8ff6',
    storageBucket: 'bundahara-a8ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr7vroak8-XTOg8wOOJL6w73RBpIiFIfE',
    appId: '1:229689037563:ios:65985837acb121cfa0965e',
    messagingSenderId: '229689037563',
    projectId: 'bundahara-a8ff6',
    storageBucket: 'bundahara-a8ff6.firebasestorage.app',
    iosBundleId: 'com.example.testingBolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr7vroak8-XTOg8wOOJL6w73RBpIiFIfE',
    appId: '1:229689037563:ios:65985837acb121cfa0965e',
    messagingSenderId: '229689037563',
    projectId: 'bundahara-a8ff6',
    storageBucket: 'bundahara-a8ff6.firebasestorage.app',
    iosBundleId: 'com.example.testingBolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARTIoDBTLeagzIsJacpt1YTiLMsfbBvYI',
    appId: '1:229689037563:web:898915fda72b8732a0965e',
    messagingSenderId: '229689037563',
    projectId: 'bundahara-a8ff6',
    authDomain: 'bundahara-a8ff6.firebaseapp.com',
    storageBucket: 'bundahara-a8ff6.firebasestorage.app',
    measurementId: 'G-D6EFD8VNCK',
  );

}